name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Vérifier le code source
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurer Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3. Installer les dépendances
    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r api/requirements.txt
        pip install --no-cache-dir pytest

    # 4. Configurer le PYTHONPATH
    - name: Set PYTHONPATH
      run: |
        echo "export PYTHONPATH=$PYTHONPATH:$(pwd)/MLflow" >> $GITHUB_ENV

    # 5. Exécuter les tests unitaires
    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/MLflow  # Ajout explicite de PYTHONPATH
        pytest test/pipeline_test.py --maxfail=1 --disable-warnings -q
        pytest test/main_test.py --maxfail=1 --disable-warnings -q

    # 6. Entraîner et logger le modèle
    - name: Train and log model
      run: |
        python MLflow/pipeline.py

    # 7. Construire l'image Docker
    - name: Build Docker image
      run: |
        docker build -t ml-api .

    # 8. Pousser l'image Docker sur DockerHub
    - name: Push Docker image to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag ml-api:latest ${{ secrets.DOCKER_USERNAME }}/ml-api:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/ml-api:latest

    # 9. Déployer l'image sur l'instance GCP
    - name: Deploy Docker image to GCP instance
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Sauvegarder la clé privée dans un fichier temporaire
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
        chmod 600 ssh_key  # Définir les bonnes permissions pour la clé privée

        # Exécuter la commande SSH
        ssh -o StrictHostKeyChecking=no -i ssh_key rafael@34.170.123.233 << 'EOF'
        docker pull ${{ secrets.DOCKER_USERNAME }}/ml-api:latest
        docker stop ml-api-container || true
        docker rm ml-api-container || true
        docker run -d --name ml-api-container -p 5001:5000 ${{ secrets.DOCKER_USERNAME }}/ml-api:latest
        EOF

        # Nettoyer la clé temporaire
        rm ssh_key
